USE [master]
GO
/****** Object:  Database [QuanlySinhVien]    Script Date: 10/3/2023 9:57:34 PM ******/
CREATE DATABASE [QuanlySinhVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanlySinhVien', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuanlySinhVien.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanlySinhVien_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuanlySinhVien_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QuanlySinhVien] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanlySinhVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanlySinhVien] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanlySinhVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanlySinhVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QuanlySinhVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanlySinhVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanlySinhVien] SET  MULTI_USER 
GO
ALTER DATABASE [QuanlySinhVien] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanlySinhVien] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanlySinhVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanlySinhVien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanlySinhVien] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanlySinhVien] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QuanlySinhVien] SET QUERY_STORE = ON
GO
ALTER DATABASE [QuanlySinhVien] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QuanlySinhVien]
GO
/****** Object:  Table [dbo].[Faculty]    Script Date: 10/3/2023 9:57:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Faculty](
	[FacultyID] [int] NOT NULL,
	[FacultyName] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Faculty] PRIMARY KEY CLUSTERED 
(
	[FacultyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Major]    Script Date: 10/3/2023 9:57:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Major](
	[FacultyID] [int] NOT NULL,
	[MajorID] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Major] PRIMARY KEY CLUSTERED 
(
	[FacultyID] ASC,
	[MajorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 10/3/2023 9:57:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[StudentID] [nvarchar](10) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[AverageScore] [float] NOT NULL,
	[FacultyID] [int] NULL,
	[MajorID] [int] NULL,
	[Avatar] [nvarchar](255) NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [QuanlySinhVien] SET  READ_WRITE 
GO

select *
from dbo.Faculty, dbo.Student, dbo.Major
where dbo.Faculty.FacultyID=dbo.